# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
#       1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

def fib():

    fib_seq = []
    term1 = 1
    term2 = 2
    
    fib_seq.append(term1)
    fib_seq.append(term2)

    #if limit <= 2:
    #    return fib_seq

    while True:
        tmp = term1 + term2
        if tmp < 4000000:
            fib_seq.append(tmp)
        else:
            break
        term1 = term2
        term2 = tmp
    
    return fib_seq

def sumOfEven(arr):
    sum = 0

    for x in arr:
        if x % 2 == 0:
            sum += x

    return sum


def main():
    num = fib()
    print(num)
    total = sumOfEven(num)
    print("Sum of even fibonicci numbers is: {}".format(total))

if __name__ == "__main__":
    main()
        